QuieroPizza/QuieroPizza.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuieroPizza.web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

QuieroPizza/QuieroPizza.web/Controllers/ProductosController.cs
using QuieroPizza.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuieroPizza.web.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Index()
        {
            var productosBL = new ProductosBL();
            var listadeProductos = productosBL.ObtenerProductos();
            return View(listadeProductos);
        }
    }
}

QuieroPizza/QuieroPizza.web/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Bienvenido a Quiero Pizza</h2>

 

QuieroPizza/QuieroPizza.web/Views/Productos/Index.cshtml
@model List<QuieroPizza.BL.Producto>
@{
    ViewBag.Title = "Index";
}

<h2>Productos</h2> 

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Codigo
                </th>
                <th>
                    Descripcion
                </th>
                <th>
                    Precio
                </th>
            </tr>
        </thead> 
        @foreach (var producto in Model)
        { 
        <tr>
           <td>@producto.Id</td>
           <td>@producto.Descripcion</td>
           <td>@producto.Precio</td>
        </tr>
        }  
    </table> 

QuieroPizza/QuieroPizza.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quiero Pizza", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio","index","Home")
                    </li>
                    <li>
                        @Html.ActionLink("Lista de Productos","index","Productos")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>